import type { ActionItem } from '../types';

export const ACTION_LIBRARY: ActionItem[] = [
  // Resety Energetyczne (SZYBKI RESET 1-5 min)
  {
    id: 'reset_cold_shower',
    triggerTags: ['Słaby sen', 'Stres', 'Zmęczenie'],
    type: 'Reset Energetyczny',
    duration: 2,
    title: 'Zimny prysznic',
    content: 'Idź pod prysznic i zrób 30 sekundowy zimny prysznic. To natychmiastowy sygnał dla ciała, by się obudziło i podniosło poziom dopaminy na +/- 3 godziny.',
    icon: '🚿',
  },
  {
    id: 'reset_sound_music',
    triggerTags: ['Praca głęboka', 'Stres', 'Zmęczenie'],
    type: 'Reset Energetyczny',
    duration: 3,
    title: 'Dźwięk i muzyka',
    content: 'Opcja 1: Puść głośno ulubioną piosenkę. Koniecznie bez słuchawek, aby dźwięk wypełnił przestrzeń.\n\nOpcja 2: Użyj aplikacji ze ścieżkami dźwiękowymi wspierającymi pracę mózgu:\n- <a href="https://endel.io/" target="_blank" rel="noopener noreferrer">Endel</a>\n- <a href="https://www.brain.fm/pl" target="_blank" rel="noopener noreferrer">Brain.fm</a>\n- <a href="https://www.youtube.com/@MindAmend" target="_blank" rel="noopener noreferrer">MindAmend</a>',
    icon: '🎶',
  },
  {
    id: 'reset_breathing_478',
    triggerTags: ['Stres', 'Spotkanie', 'Przytłoczenie'],
    type: 'Technika oddechowa',
    duration: 2,
    title: 'Weź oddech (4-7-8)',
    content: 'Zastosuj technikę 4-7-8:\n- 4 sekundy wdechu\n- 7 sekund wstrzymania\n- 8 sekund wydechu\nPowtarzaj przez co najmniej 2 minuty, aby osiągnąć zamierzony efekt.',
    icon: '🌬️',
    breathingPattern: '478',
  },
  {
    id: 'reset_breathing_4784',
    triggerTags: ['Stres', 'Skupienie', 'Relaks'],
    type: 'Technika oddechowa',
    duration: 3,
    title: 'Oddech pudełkowy (4-7-8-4)',
    content: 'Zastosuj technikę 4-7-8-4:\n- 4 sekundy wdechu\n- 7 sekund wstrzymania po wdechu\n- 8 sekund wydechu\n- 4 sekundy wstrzymania po wydechu\nPowtarzaj przez co najmniej 2 minuty.',
    icon: '📦',
    breathingPattern: '4784',
  },
  {
    id: 'reset_change_clothes',
    triggerTags: ['Relaks', 'Przytłoczenie'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Zmień ubranie',
    content: 'Zmiana ubrania może być szybkim sygnałem dla mózgu, aby zmienić tryb i odświeżyć stan umysłu.',
    icon: '👕',
  },
  {
    id: 'reset_change_task',
    triggerTags: ['Praca głęboka', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Zmień zadanie',
    content: 'Czasem nie możesz się zabrać za to konkretne zadanie. Zmiana (nawet na chwilę) zadania na inne może dać szybki reset i przywrócić energię.',
    icon: '🔄',
  },
  {
    id: 'reset_clean_desk',
    triggerTags: ['Praca głęboka', 'Stres', 'Przytłoczenie'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Posprzątaj biurko',
    content: 'Poświęć minutę na uporządkowanie przestrzeni wokół siebie. Czyste otoczenie sprzyja skupieniu.',
    icon: '✨',
  },
  {
    id: 'reset_change_room',
    triggerTags: ['Praca głęboka', 'Relaks', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Przenieś się do innego pokoju',
    content: 'Czasem wystarczy zmiana otoczenia, aby poczuć się lepiej i odzyskać perspektywę.',
    icon: '🚪',
  },
  {
    id: 'reset_oxygen',
    triggerTags: ['Posiłek', 'Słaby sen', 'Zmęczenie', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Więcej tlenu!',
    content: 'Przewietrz mieszkanie lub włącz klimatyzację. Świeże powietrze to natychmiastowy zastrzyk energii dla mózgu.',
    icon: '💨',
  },
  {
    id: 'reset_fullscreen',
    triggerTags: ['Praca głęboka', 'Przytłoczenie'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Tryb pełnoekranowy',
    content: 'Włącz go w aplikacji, nad którą pracujesz. Ukrycie wszystkich rozpraszaczy z pola widzenia pomaga w pełni skupić się na zadaniu.',
    icon: '🖥️',
  },
  {
    id: 'reset_block_distractions',
    triggerTags: ['Praca głęboka', 'Stres', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 1,
    title: 'Blokuj, nie walcz',
    content: 'Jeśli masz problem ze skupieniem i uciekasz do innych stron, zablokuj je. Nie trać energii na walkę z chęcią przełączenia karty.\n\nPolecane aplikacje:\n- <a href="https://freedom.to/dashboard" target="_blank" rel="noopener noreferrer">Freedom</a>\n- <a href="https://www.opal.so/" target="_blank" rel="noopener noreferrer">Opal</a>',
    icon: '🛡️',
  },
  {
    id: 'reset_intelligent_pomodoro',
    triggerTags: ['Praca głęboka', 'Skupienie', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 5,
    title: 'Inteligentne Pomodoro',
    content: 'Ustal, na jak długo chcesz się skupić (np. 25 minut).\n\nPo tym czasie oceń swój poziom skupienia:\n- Rozproszony\n- OK\n- Dobry\n- Flow\n\nJeśli osiągnąłeś \'Flow\', kontynuuj pracę przez kolejne 5-15 minut, a następnie ponownie oceń. Jeśli nie, zrób sobie 5-minutową przerwę.',
    icon: '🍅',
  },
  // Resety Energetyczne (SZYBKI RECHARGE 10-15 min)
  {
    id: 'recharge_braindump_walk',
    triggerTags: ['Stres', 'Praca głęboka', 'Przytłoczenie', 'Brain Fog'],
    type: 'Reset Energetyczny',
    duration: 15,
    title: 'Spacerowy “BrainDump”',
    content: 'Użyj aplikacji do transkrypcji audio i podczas spaceru wyrzuć z siebie wszystko, co siedzi Ci w głowie. To daje mocny zastrzyk energii.\n\nPolecane aplikacje:\n- <a href="https://apps.apple.com/us/app/voicepal-your-ai-ghostwriter/id6471552007" target="_blank" rel="noopener noreferrer">VoicePal</a>\n- <a href="https://superwhisper.com/" target="_blank" rel="noopener noreferrer">Superwhisper</a>\n- <a href="https://voicenotes.com/app" target="_blank" rel="noopener noreferrer">VoiceNotes</a>',
    icon: '🧠',
  },
  {
    id: 'recharge_walk_no_phone',
    triggerTags: ['Relaks', 'Spotkanie', 'Stres'],
    type: 'Reset Energetyczny',
    duration: 15,
    title: 'Spacer bez telefonu',
    content: 'Chodzenie to fundament pracy mózgu. Obserwowanie otoczenia (drzew, chmur, budynków) i poruszanie gałkami ocznymi synchronizuje obie półkule mózgowe.',
    icon: '🚶‍♂️',
  },
  {
    id: 'recharge_nsdr',
    triggerTags: ['Słaby sen', 'Stres', 'Zmęczenie'],
    type: 'Reset Energetyczny',
    duration: 10,
    title: 'NSDR (Non-Sleep Deep Rest)',
    content: 'Ta metoda może podnieść poziom dopaminy i sprawić, że poczujesz się świetnie. Jest doskonałą alternatywą dla medytacji.',
    icon: '🧘',
  },
  {
    id: 'recharge_create_something',
    triggerTags: ['Relaks', 'Przytłoczenie'],
    type: 'Reset Energetyczny',
    duration: 15,
    title: 'Stwórz coś kreatywnego',
    content: 'Zrób coś, co lubisz. Narysuj coś, ułóż puzzle, złóż lego. Tworzenie czegoś to potężny sposób na regenerację mentalną.',
    icon: '🎨',
  },
  // Protokoły Ruchowe
  {
    id: 'protocol_morning_kickstarter',
    triggerTags: ['Trening', 'Słaby sen', 'Zmęczenie'],
    type: 'Protokół Ruchowy',
    duration: 10,
    title: 'Poranny Kickstarter',
    content: 'Zestaw ćwiczeń mobilizacyjnych na idealny początek dnia. Rozruszaj zastałe po nocy ciało i przygotuj je do działania.',
    icon: '☀️',
    videoUrl: 'https://player.vimeo.com/video/902862846?h=2dd0b8bec5&autoplay=1&loop=1&title=0&byline=0&portrait=0',
  },
  {
    id: 'protocol_reboot_shake_it',
    triggerTags: ['Spotkanie', 'Stres', 'Zmęczenie'],
    type: 'Protokół Ruchowy',
    duration: 5,
    title: 'Energetyczny Reboot - Shake It',
    content: 'Szybki i dynamiczny protokół, aby rozruszać ciało, pozbyć się napięcia i natychmiast podnieść poziom energii.',
    icon: '💃',
    videoUrl: 'https://player.vimeo.com/video/902862846?h=2dd0b8bec5&autoplay=1&loop=1&title=0&byline=0&portrait=0',
  },
  {
    id: 'protocol_reboot_reset',
    triggerTags: ['Praca głęboka', 'Posiłek', 'Stres', 'Przytłoczenie'],
    type: 'Protokół Ruchowy',
    duration: 5,
    title: 'Energetyczny Reboot - Reset',
    content: 'Skoncentrowany na oddechu i delikatnym ruchu protokół, który pomaga zresetować układ nerwowy i odzyskać spokój.',
    icon: '🔄',
    videoUrl: 'https://player.vimeo.com/video/902862846?h=2dd0b8bec5&autoplay=1&loop=1&title=0&byline=0&portrait=0',
  },
  {
    id: 'protocol_reboot_pumpfocus',
    triggerTags: ['Praca głęboka', 'Trening', 'Brain Fog'],
    type: 'Protokół Ruchowy',
    duration: 5,
    title: 'Reboot - PumpFocus',
    content: 'Intensywny protokół, który ma za zadanie maksymalnie dotlenić mózg i przygotować Cię do głębokiej pracy wymagającej skupienia.',
    icon: '⚡',
    videoUrl: 'https://player.vimeo.com/video/902862846?h=2dd0b8bec5&autoplay=1&loop=1&title=0&byline=0&portrait=0',
  },
  {
    id: 'protocol_reboot_brainflow',
    triggerTags: ['Praca głęboka', 'Skupienie', 'Brain Fog'],
    type: 'Protokół Ruchowy',
    duration: 6.5,
    title: 'Reboot - BrainFlow',
    content: 'Protokół stworzony, aby pobudzić krążenie i dotlenić mózg, idealny przed sesją głębokiej pracy lub gdy dopada Cię mgła mózgowa.',
    icon: '🧠',
    workout: [
      { type: 'exercise', exerciseId: 'ex002', duration: 60 },
      { type: 'rest', duration: 30 },
      { type: 'exercise', exerciseId: 'ex001', duration: 45 },
      { type: 'rest', duration: 30 },
      { type: 'exercise', exerciseId: 'ex003', duration: 60 },
      { type: 'rest', duration: 30 },
      { type: 'exercise', exerciseId: 'ex002', duration: 45 },
      { type: 'rest', duration: 30 },
      { type: 'exercise', exerciseId: 'ex001', duration: 60 },
    ]
  }
  
];